### ISSUE TITLE
ctrl + enter is not working

### ISSUE THREAD

**Issue by pedrovinicius** [carlosbaraza/yard#2]
Hello, I'm trying to use your plugin on Linux, but the command for generate the code is not working... 
[ ctrl + enter ] only breaks the line... :neutral_face:

**Comment by carlosbaraza** [comment]
Hi @pedrovinicius,

Thank you for reporting the issue. If you have some time, feel free to submit a fix to the issue.

Carlos.

**Comment by sdzyba** [comment]
Hi.

In case if someone will come here searching the solution, here's a workaround.
You can disable default newline adding behavior. To do this add following to your own custom Keymap:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-enter': 'unset!'
```

**Comment by mityakoval** [comment]
Doesn't work on macOS as well. `ctrl` + `Enter` doesn't do anything. `cmd` + `Enter` just breaks the line

**Comment by jorgefuertes** [comment]
It doesn't work in osx and I've tried adding another key combination:

```javascript
'atom-workspace':
  'ctrl-y': 'yard:create'
```

But it throws the following error when stroked:

`Uncaught TypeError: Cannot read property '24' of undefined`

**Comment by nimylian** [comment]
This is fixed for the current version of OS X. I'm considering changing the default key combination, but I'm open to suggestions.
